// Generated by scripts/generate-validation-policy.py; edit docs/validation-policy.json.
namespace Enterprise.Application.Common.Validation;

public static class ValidationPolicy
{
    public const int EmailMax = 254;
    public const int NameMax = 100;
    public const int CompanyMax = 200;
    public const int TitleMax = 200;
    public const int RoleNameMax = 100;
    public const int DescriptionMax = 2000;
    public const int PhoneMax = 40;
    public const int PhoneDigitsMin = 7;
    public const int PhoneDigitsMax = 15;
    public const int PasswordMin = 8;
    public const int PasswordMax = 128;
    public const int OtpLength = 6;
    public const int SkuMax = 50;
    public const int CodeMax = 100;
    public const int SearchMax = 200;
    public const int DisplayOrderMax = 2147483647;
    public const int QuantityMax = 999;
    public const decimal PriceMax = 999999.99m;
    public const int TokenMax = 4096;
    public const int SessionIdMax = 255;
    public const int ImageMaxBytes = 2097152;
    public const int PageSizeMax = 100;
    public const int DeviceTokenMax = 512;
    public const int ExternalTokenMax = 8192;
    public const int WebhookMaxBytes = 1048576;
}
