from pathlib import Path
import json
root = Path(__file__).resolve().parents[1]
policy = json.loads((root / 'docs/validation-policy.json').read_text())
cs = '// Generated by scripts/generate-validation-policy.py; edit docs/validation-policy.json.\nnamespace Enterprise.Application.Common.Validation;\n\npublic static class ValidationPolicy\n{\n'
for key, value in policy.items():
    cs += f'    public const {"decimal" if isinstance(value, float) else "int"} {key} = {value}{"m" if isinstance(value, float) else ""};\n'
cs += '}\n'
(root / 'src/Enterprise.Application/Common/Validation/ValidationPolicy.cs').write_text(cs)
(root / 'frontend/subito-web/src/app/shared/forms/validation-policy.ts').write_text('// Generated by scripts/generate-validation-policy.py; edit docs/validation-policy.json.\nexport const VALIDATION_POLICY = ' + json.dumps(policy, indent=2) + ' as const;\n')
